Railsテキスト教材一覧ページの実装
yanbaru-expert/team_project_62 pull request #40
Opened 2022-05-12 18:59 UTC by kuramoto30

close #15 

## 実装内容
 - `app/models/text.rb` に次を定義
 ```
RAILS_GENRE_LIST = %w[basic git ruby rails]
```
 - Railsテキスト教材の一覧ページを作成
   - 表示するジャンルは Text::RAILS_GENRE_LIST に制限
   - Bootstrapの Cards や Grid System を用いる
   - each を使わず「コレクションをレンダリング」を利用
   - 画像部分は デフォルト画像 を表示するのみとする
   - カードの height, max-width を指定する
   - 「読破済みボタン」はボタンの配置のみとする

## 確認内容
 - レスポンシブ対応ができているかどうかを確認
 - ブラウザの横幅次第でカードの横幅が長くなりすぎていないか確認
 - PHPのテキスト教材が表示されていないことを確認
## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
- [ ] `rubocop -a` を実行

2022-05-12 19:04 UTC, kuramoto30 commented on app/models/text.rb
> +  RAILS_GENRE_LIST = %w[basic git ruby rails].freeze
`rubocop -a`を実施するとfreezeするよう指示があり`.freeze`を記述しました。

2022-05-12 19:04 UTC, kuramoto30 commented on app/views/texts/_text.html.erb
> +          【<%= text.genre.capitalize %>】
一覧表示されるコンテンツのジャンル名が全て小文字だったため`capitalizeメソッド`を使用しました。

2022-05-13 10:43 UTC, great084 requested changes
テキスト一覧画面を見ると、コンテンツが二乗で出力されています。
どこに原因があるかは、突き止めて、修正してみてください。

その他の指摘は以下についきしています。

2022-05-13 10:43 UTC, great084 commented on app/controllers/texts_controller.rb
> +             end
データを絞るのはmodel側で実施しましょう。

2022-05-13 10:43 UTC, great084 commented on app/models/text.rb
> +  RAILS_GENRE_LIST = %w[basic git ruby rails].freeze
定義したRAILS_GENRE_LISTを使用して、データ対象の絞り込みを取得しましょう。

2022-05-13 10:43 UTC, great084 commented on app/views/texts/_text.html.erb
> +          【<%= text.genre.capitalize %>】
ここは小文字ではなく、別途定義したgenreの日本語化の値を出すようにしてください。

2022-05-18 02:09 UTC, kuramoto30 commented on app/assets/stylesheets/texts.scss
> +.card {
textのみに反映させるCSSのためこちらに記述し直しました。

2022-05-18 02:09 UTC, kuramoto30 commented on app/views/texts/_text.html.erb
> -  <% @texts.each do |text| %>
renderを使用して繰り返し処理するため削除しました。

2022-05-18 15:28 UTC, great084 commented on app/models/text.rb
> +    PHP: 5
原因これですね。
RAILS_GENRE_LISTに定義した値と、enumの値が一致してないからです。
enum genreの設定値は変更してはだめですよ〜

2022-05-19 22:25 UTC, great084 commented on app/views/texts/_text.html.erb
> +          <button type="button" class="btn btn-secondary btn-md btn-block">読破済み</button>
「読破済みにする」としてください。

2022-05-19 22:25 UTC, great084 commented on app/assets/stylesheets/texts.scss
> +.card {
.card クラスはbootstrapであからかじめ定義されているクラスですので、上書き更新は避けたほうが良いです。
（他の画面で cardコンポーネントを使おうと思ったら、意図せずこの上書き内容が反映されてしまうため）
新たに以下のCSS属性を設定したクラスを定義して、それを該当htmlタグに設定してあげるのが無難です。

2022-05-21 05:17 UTC, kuramoto30 commented on app/assets/stylesheets/texts.scss
> +.content-card {
新たにクラスを定義しました。

2022-05-22 02:00 UTC, great084 approved these changes
![エンジニアを褒めるネコ:いいね](https://raw.githubusercontent.com/fukayatsu/lttm-crx/master/vendor/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%82%92%E8%A4%92%E3%82%81%E3%82%8B%E3%83%8D%E3%82%B3/33_%E3%81%84%E3%81%84%E3%81%AD.png)

2022-05-25 02:58 UTC, merged